@localhost = http://localhost:8000
@localhostV0 = http://localhost:8000/api/v0
@localhostV1 = http://localhost:8000/api/v1
@localhostV2 = http://localhost:8000/api/v2

# ________________________________________ test

### Index route
GET {{localhost}}/

### Health Check
GET {{localhost}}/health

### Ping/Pong route for testing functionality
GET {{localhostV0}}/ping

# ________________________________________ user

### Get all users
GET {{localhostV1}}/users

# ________________________________________ book

### Create a new book
POST {{localhostV1}}/books
Content-Type: application/json

{
  "title": "The Great Gatsby",
  "author": "F. Scott Fitzgerald",
  "published_year": 1925
}

### Get all books
GET {{localhostV1}}/books

### Get a specific book by ID
GET {{localhostV1}}/books/:id

### Delete a specific book by ID
DELETE {{localhostV1}}/books/:id
